# Dark background
# background #202020
# foreground #f7f7f7

# ===== Font =====
font_family Fira Code
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        13.0


# Transparency level
background_opacity 0.8
background_blur 1

window_padding_width 6


# BEGIN_KITTY_THEME
# IC Orange PPL
include current-theme.conf
# END_KITTY_THEME
